version: "3.8"  # Defina a versão do Docker Compose

services:
    ocateca-db:
        restart: always
        image: bitnami/mariadb:10.10.6
        ports:
            - "3306:3306"
        volumes:
            - data:/home/ocateca/database/mariadb
        environment:
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_ROOT_PASSWORD=21323182xxxhjkhdfjkskfjsd379231
volumes:
    data: {}
